package com.turn.inscription.dao.mapper;

import com.turn.inscription.dao.entity.InscriptionHolder;
import com.turn.inscription.dao.entity.InscriptionHolderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InscriptionHolderMapper {
    long countByExample(InscriptionHolderExample example);

    int deleteByExample(InscriptionHolderExample example);

    int deleteByPrimaryKey(String inscriptionId);

    int insert(InscriptionHolder record);

    int insertSelective(InscriptionHolder record);

    List<InscriptionHolder> selectByExample(InscriptionHolderExample example);

    InscriptionHolder selectByPrimaryKey(String inscriptionId);

    int updateByExampleSelective(@Param("record") InscriptionHolder record, @Param("example") InscriptionHolderExample example);

    int updateByExample(@Param("record") InscriptionHolder record, @Param("example") InscriptionHolderExample example);

    int updateByPrimaryKeySelective(InscriptionHolder record);

    int updateByPrimaryKey(InscriptionHolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inscription_holder
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<InscriptionHolder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inscription_holder
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<InscriptionHolder> list, @Param("selective") InscriptionHolder.Column ... selective);
}