package com.turn.inscription.dao.mapper;

import com.turn.inscription.dao.entity.Inscription;
import com.turn.inscription.dao.entity.InscriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InscriptionMapper {
    long countByExample(InscriptionExample example);

    int deleteByExample(InscriptionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Inscription record);

    int insertSelective(Inscription record);

    List<Inscription> selectByExample(InscriptionExample example);

    Inscription selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Inscription record, @Param("example") InscriptionExample example);

    int updateByExample(@Param("record") Inscription record, @Param("example") InscriptionExample example);

    int updateByPrimaryKeySelective(Inscription record);

    int updateByPrimaryKey(Inscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inscription
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Inscription> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inscription
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Inscription> list, @Param("selective") Inscription.Column ... selective);
}